issuers:
  bcreg:
    name: BC Corporate Registry
    abbreviation: BCReg
    url: "https://www2.gov.bc.ca/gov/content/governments/organizational-structure/\
      ministries-organizations/ministries/citizens-services/bc-registries-online-services"
    email: bcreg.test.issuer@example.ca
    url: $APPLICATION_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      seed: $WALLET_SEED_BCREG

    credential_types:
      - description: Registration
        schema: registration.bc_registries
        issuer_url: $APPLICATION_URL_INCORP
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        mapping:
          - model: name
            fields:
              text:
                input: entity_name
                from: claim
              type:
                input: entity_name
                from: value

      - description: Relationship
        schema: relationship.bc_registries
        issuer_url: $APPLICATION_URL_DBA
        topic:
          related_source_id:
            input: associated_registration_id
            from: claim
          related_type:
            input: registration
            from: value
          source_id:
            input: registration_id
            from: claim
          type:
            input: relationship
            from: value

      - description: Corporate Address
        schema: address.bc_registries
        issuer_url: $APPLICATION_URL_ADDRESS
        topic:
          source_id:
            input: registration_id
            from: claim
          type:
            input: registration
            from: value
        cardinality_fields:
          - address_type
        mapping:
          - model: address
            fields:
              addressee:
                input: addressee
                from: claim
              civic_address:
                input: civic_address
                from: claim
              city:
                input: municipality
                from: claim
              province:
                input: province
                from: claim
              postal_code:
                input: postal_code
                from: claim
              country:
                input: country
                from: claim
              type:
                input: address_type
                from: claim

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  registration:
    version: '1.0.0'
    schemas:
      - key:
          # did: DtjQTjwNq7ZyStCE7zwL4r
          name: registration.bc_registries
          version: '1.0.32'
        attributes:
          - registration_id
          - entity_name
          - entity_name_effective
          - entity_name_assumed
          - entity_name_assumed_effective
          - entity_name_trans
          - entity_name_trans_effective
          - entity_status
          - entity_status_effective
          - entity_type
          - registered_jurisdiction
          - registration_type
          - home_jurisdiction
          - effective_date
